version: '2'
services:
  gatling-runner:
    image: j5ik2o-aws-gatling-tools/gatling-runner:latest
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_PROFILE=thread-weaver
      - GATLING_SIMULATION_CLASS=com.github.j5ik2o.gatling.BasicSimulation
      - GATLING_EXECUTION_ID=default
      - GATLING_USERS=1
      - GATLING_RAMP_DURATION=1m
      - GATLING_HOLD_DURATION=2m
      - GATLING_S3_BUCKET_NAME=j5ik2o-aws-gatling-tools-logs
      - GATLING_RESULT_DIR=target/gatling
      - GATLING_ENDPOINT_BASE_URL=http://10.0.1.7:18080/v1
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials
